#!/bin/bash
options='-diag-file=diagnostics.diag -nologo -O2 -fpscomp general -warn declarations -warn unused -warn uncalled -warn interfaces -save -init=zero -fpe0 -fp-model source -fPIC -c '
ifx $options ttutilprefs.f90
ifx $options ttutil.f90
ifx $options rdmodulettutil.f90
ifx $options dtnow.f90
ifx $options fatalerr.f90
ifx $options fopengstandard.f90
ifx $options ifindc.f90
ifx $options messini.f90
ifx $options messinq.f90
ifx $options newlinestandard.f90
ifx $options openlogf.f90
ifx $options outar2.f90
ifx $options outdat.f90
ifx $options outsel.f90
ifx $options recread.f90
ifx $options recreadi.f90
ifx $options recreadt.f90
ifx $options upperc.f90
ifx $options addinf.for
ifx $options addint.for
ifx $options addrea.for
ifx $options addref.for
ifx $options addstf.for
ifx $options addstr.for
ifx $options ambusy.for
ifx $options copfl2.for
ifx $options decchk.for
ifx $options decdou.for
ifx $options decint.for
ifx $options decrea.for
ifx $options decrec.for
ifx $options dectim.for
ifx $options delfil.for
ifx $options dtardp.for
ifx $options dtdpar.for
ifx $options dtdpst.for
ifx $options dtfsecmp.for
ifx $options dtfsedp.for
ifx $options dtleap.for
ifx $options dtsys.for
ifx $options entcha.for
ifx $options entdch.for
ifx $options entddo.for
ifx $options entdin.for
ifx $options entdou.for
ifx $options entdre.for
ifx $options entdti.for
ifx $options entdyn.for
ifx $options enthlp.for
ifx $options entint.for
ifx $options entrea.for
ifx $options enttim.for
ifx $options entyno.for
ifx $options extens.for
ifx $options flexist.for
ifx $options flname.for
ifx $options fopens.for
ifx $options getrec.for
ifx $options getun.for
ifx $options getun2.for
ifx $options ifindi.for
ifx $options istart.for
ifx $options iunifl.for
ifx $options lint.for
ifx $options lowerc.for
ifx $options messwrt.for
ifx $options movavr.for
ifx $options notnul.for
ifx $options outcom.for
ifx $options outplt.for
ifx $options parsword.for
ifx $options rchrsrc.for
ifx $options rdacha.for
ifx $options rdador.for
ifx $options rdadou.for
ifx $options rdainr.for
ifx $options rdaint.for
ifx $options rdalog.for
ifx $options rdarea.for
ifx $options rdarer.for
ifx $options rdatim.for
ifx $options rddata.for
ifx $options rddtmp.for
ifx $options rderr.for
ifx $options rderri.for
ifx $options rdfcha.for
ifx $options rdfdor.for
ifx $options rdfdou.for
ifx $options rdfinr.for
ifx $options rdfint.for
ifx $options rdflog.for
ifx $options rdfrea.for
ifx $options rdfrer.for
ifx $options rdfrom.for
ifx $options rdftim.for
ifx $options rdinar.for
ifx $options rdindt.for
ifx $options rdindx.for
ifx $options rdinit.for
ifx $options rdinlv.for
ifx $options rdinne.for
ifx $options rdinqr.for
ifx $options rdinqr2.for
ifx $options rdinqr3.for
ifx $options rdlex.for
ifx $options rdmcha.for
ifx $options rdmdef.for
ifx $options rdmdou.for
ifx $options rdmint.for
ifx $options rdmlog.for
ifx $options rdmrea.for
ifx $options rdmtim.for
ifx $options rdpars.for
ifx $options rdscha.for
ifx $options rdsctb.for
ifx $options rdsdor.for
ifx $options rdsdou.for
ifx $options rdsets.for
ifx $options rdsinr.for
ifx $options rdsint.for
ifx $options rdslog.for
ifx $options rdsrea.for
ifx $options rdsrer.for
ifx $options rdstim.for
ifx $options rdtmp1.for
ifx $options rdtmp2.for
ifx $options reaand.for
ifx $options reanor.for
ifx $options remove.for
ifx $options sfindg.for
ifx $options sortch.for
ifx $options sortin.for
ifx $options str_copy.for
ifx $options swpi4.for
ifx $options ttuver.for
ifx $options unifl.for
ifx $options usedun.for
ifx $options ver4_27.for
ifx $options warning.for
ifx $options words.for
ifx $options wracha.for
ifx $options wradou.for
ifx $options wraint.for
ifx $options wralog.for
ifx $options wrarea.for
ifx $options wratim.for
ifx $options wrinit.for
ifx $options wrscha.for
ifx $options wrsdou.for
ifx $options wrsint.for
ifx $options wrslog.for
ifx $options wrsrea.for
ifx $options wrstim.for
ar rc ttutil427.a *.o
chmod 777 ttutil427.a